### ISSUE TITLE
Mugshot Enhancement? 

### ISSUE THREAD

**Issue by techniciantucker** [jonassvensson4/jsfour-idcard#22]
Any plans to add ped mugshots to the id cards?

**Comment by jonassvensson4** [comment]
I'm open for suggestions. There's currently no way (that I'm aware of) to send the player mugshot to the NUI since the mugshot is stored internally.

Which leads to 3 options.
1. Use the screenshot_basic resource that works 50% of the time to take a screenshot of the screen. Might want to tweak the resource to take a screenshot of a selected area rather than the whole screen.
2. Use an external screenshot program and let the players take the screenshot themselves. Maybe add that feature to the the police job? When a new player joins the server, make them go to the police station to get an ID. The police officer would then take a screenshot of the player, upload it somewhere and then grab the link. It would then be possible to use that image instead of the default black one.
3. Display the mugshot through the client using the DrawSprite native and play around with the xy values. Would probably be possible but ugly.

**Comment by techniciantucker** [comment]
Here's an example using sprite I found but have not gave it a try. 

      --CLIENT
SetEntityAsMissionEntity (GetPlayerPed (-1))
local PED_ID = NetworkGetNetworkIdFromEntity (GetPlayerPed (-1))
TriggerServerEvent (‘jsfour-idcard: open’, playerTarget, PED_ID)
server side:
--SERVER
RegisterNetEvent (“jsfour-idcard: open”)
AddEventHandler (“jsfour-idcard: open”, function (PED_ID)
local handle = RegisterPedheadshot (PED_ID)
while not IsPedheadshotReady (handle) do
Wait (100)
end
local headshot = GetPedheadshotTxdString (handle)
while true do
Wait (20)
DrawSprite (headshot, headshot, 0.40, 0.4, 0.09, 0.18, 0.0, 255, 255, 255, 1000)
end
end)

**Comment by jonassvensson4** [comment]
Yeah that's option 3. You'll have to play around with the xy values since every client have different resolutions.

This isn't something I will add since it takes a lot of time. I would prefer the 2 other options since it makes things easier. 

Feel free to fork it and add it :)
