### ISSUE TITLE
Can't show ID card

### ISSUE THREAD

**Issue by Sziszkaaa675** [jonassvensson4/jsfour-idcard#36]
When I join the server, or restart the script, it will show my ID card, but if I press any button, its dissaper, and never come back.

**Comment by jnsvns** [comment]
How are you trying to show it?

**Comment by Sziszkaaa675** [comment]
if you can give me your discord, it meant rhe world to me, because I'm bad at explayning in writing

**Comment by Sziszkaaa675** [comment]
So if its not a problem for you if you help me on discord?

**Comment by jnsvns** [comment]
You don't really need to explain anything, uploading your client-sided code to pastebin, hastebin or something like that would be enough

**Comment by Sziszkaaa675** [comment]
ok, just one sec, thank you

**Comment by Sziszkaaa675** [comment]
https://pastebin.com/4BNvzxRK here it is

**Comment by jnsvns** [comment]
You can't just copy and paste everything you find in the readme file. 

As you said earlier, you'll see the ID card once you start/restart the resource but never again. Why? Because you've just pasted all of the events inside the client file. By doing that it will run immediately on startup and never again.

You need to add a key-event or add the triggers to an already existing menu. If you don't know how you're supposed to do that you can have a look at the pastebin link that you'll find under [usages](https://github.com/jonassvensson4/jsfour-idcard#usage)
