### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by RPUK1** [jonassvensson4/jsfour-idcard#41]
Is there a way to make commands from this

for example

/showID  

Wanthing to add these to a radial menu

**Comment by jnsvns** [comment]
Of course. Just trigger the events with a command

**Comment by RPUK1** [comment]
Hi

 

Tried that,  struggling to make it work

 

Any chance you could give me an example ?


Appreciate your help

 
 

Sent: Monday, May 04, 2020 at 3:45 PM

**Comment by jnsvns** [comment]
Let me see what you've tried so far

**Comment by RPUK1** [comment]
RegisterCommand('showID', function()
            if distance ~= -1 and distance <= 3.0 then
                TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(PlayerId()), GetPlayerServerId(player), 'driver')
            else
                ESX.ShowNotification('No players nearby')
            end
)

 

 

Sent: Thursday, May 07, 2020 at 1:16 PM

**Comment by RPUK1** [comment]
I've tried a few things along the lines of

 

 


RegisterCommand('showID', function()
            if distance ~= -1 and distance <= 3.0 then
                TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(PlayerId()), GetPlayerServerId(player), 'driver')
            else
                ESX.ShowNotification('No players nearby')
            end
)

 


 
 

Sent: Thursday, May 07, 2020 at 1:16 PM

**Comment by jnsvns** [comment]
I can't see where you've defined distance nor player so that won't work. You're also missing an end at the bottom.

I suggest you'll have a look at the fivem docs to see how you're supposed to use the RegisterCommand function to get that part working: https://docs.fivem.net/docs/scripting-manual/migrating-from-deprecated/creating-commands/

You'll then need to define the distance and player variable. It should then work. 

You have everything you need at the docs and in my readme.
Good luck
