### ISSUE TITLE
License an item ? 

### ISSUE THREAD

**Issue by ineokb** [jonassvensson4/jsfour-idcard#42]
Hello, I would like to create an item instead of showing the permit via a menu. A permit which would be specific to each one who would display like the Jsfour currently, roughly make it into an item, an idea of how I could take it? And possibly be able to create fake paper.

**Comment by jnsvns** [comment]
I guess you would need to use some inventory system that makes it possible for you to create items that lets you store data in them. I don't know if there's a released resource that does that.

This resource does only require the player ID to be able to fetch the users information. If you want to add the abillity to fake this you would need to tweak the server event. Maybe add another varible to it? `AddEventHandler('jsfour-idcard:open', function(ID, targetID, type, fake)` Check if it's supposed to use the fake one or not and send some random data instead of the fetched one.

I'm not sure how I'm supposed to provide any morre help. This feature would mainly need the inventory system that lets you store data in each item. If you already have a system like that this should be fairly easy to create.
