### ISSUE TITLE
Problem with the weapon license

### ISSUE THREAD

**Issue by OnigamerOne** [jonassvensson4/jsfour-idcard#6]
Hi, I'm trying to use your script and implement it in my server but when I tryed it for the first time I seen that when I try to see my weapon license the script show me the license, but I never bought a weapon license

**Comment by jonassvensson4** [comment]
There's nothing in the script that checks if you actually have a license or not. The script only provides a way of showing the different types of IDs. 

It's up to the end-user to configure the script and that's why there's no menu or button events included in the script. So if you wan't it to check if you have a specified license you have to add it yourself.
